import type { TField, TParsedCollection } from './parse';

const HEADER = (
  source: string,
) => `// AUTO-GENERATED by scripts/codegen/firestore. DO NOT EDIT.
// Source: ${source}
`;

const tsType = (f: TField): string => {
  let base: string;
  switch (f.kind.kind) {
    case 'string':
      base = 'string';
      break;
    case 'number':
      base = 'number';
      break;
    case 'boolean':
      base = 'boolean';
      break;
    case 'timestamp':
      base = 'string';
      break;
    case 'vector':
      base = 'number[]';
      break;
    case 'enum':
      base = f.kind.values.map(v => `'${v}'`).join(' | ');
      break;
  }
  if (f.nullable) base += ' | null';
  return base;
};

const zodExpr = (f: TField): string => {
  let base: string;
  switch (f.kind.kind) {
    case 'string':
    case 'timestamp':
      base = 'z.string()';
      break;
    case 'number':
      base = 'z.number()';
      break;
    case 'boolean':
      base = 'z.boolean()';
      break;
    case 'vector':
      base = 'z.array(z.number())';
      break;
    case 'enum':
      base = `z.enum([${f.kind.values.map(v => `'${v}'`).join(', ')}])`;
      break;
  }
  if (f.nullable) base += '.nullable()';
  return base;
};

export function emitClient(c: TParsedCollection, sourcePath: string): string {
  const T = `T${c.typeName}`;
  const TCreate = `T${c.typeName}CreateInput`;
  const TPatch = `T${c.typeName}UpdatePatch`;
  const TFilter = `T${c.typeName}ListFilter`;
  const KEY = c.name;

  const userFields = c.fields.filter(
    f => !c.managed.includes(f.name) && f.name !== c.ownerField,
  );

  const hasTimestamp = c.fields.some(
    f => f.kind.kind === 'timestamp' || c.managed.includes(f.name),
  );
  const hasVector = c.fields.some(f => f.kind.kind === 'vector');

  const firestoreImports = [
    'collection',
    'query',
    'where',
    'orderBy',
    'limit as fbLimit',
    'getDocs',
    'getDoc',
    'addDoc',
    'updateDoc',
    'deleteDoc',
    'doc',
    'serverTimestamp',
  ];
  if (hasTimestamp) firestoreImports.push('Timestamp');
  if (hasVector) {
    firestoreImports.push('vector');
    firestoreImports.push('VectorValue');
  }

  const orderBy = c.defaultOrderBy ?? { field: 'createdAt', dir: 'desc' };

  const modelFieldLines = c.fields
    .map(f => `  ${f.name}: ${tsType(f)};`)
    .join('\n');

  const createFieldLines = userFields
    .map(f => `  ${f.name}${f.optional ? '?' : ''}: ${tsType(f)};`)
    .join('\n');

  const docSchemaLines = c.fields
    .map(f => `  ${f.name}: ${zodExpr(f)},`)
    .join('\n');

  const fromDocLines = c.fields
    .map(f => {
      if (f.kind.kind === 'timestamp') {
        if (c.managed.includes(f.name)) {
          return `    ${f.name}: tsToIso(data.${f.name}) ?? '',`;
        }
        return `    ${f.name}: tsToIso(data.${f.name}),`;
      }
      if (f.kind.kind === 'vector') {
        return `    ${f.name}: vecToArray(data.${f.name}),`;
      }
      if (f.nullable) {
        return `    ${f.name}: data.${f.name} ?? null,`;
      }
      return `    ${f.name}: data.${f.name},`;
    })
    .join('\n');

  const toCreateLines = userFields
    .map(f => {
      if (f.kind.kind === 'timestamp') {
        if (f.nullable) {
          return `    ${f.name}: input.${f.name} === null ? null : Timestamp.fromDate(new Date(input.${f.name})),`;
        }
        return `    ${f.name}: Timestamp.fromDate(new Date(input.${f.name})),`;
      }
      if (f.kind.kind === 'vector') {
        if (f.nullable) {
          return `    ${f.name}: input.${f.name} === null ? null : vector(input.${f.name}),`;
        }
        return `    ${f.name}: vector(input.${f.name}),`;
      }
      return `    ${f.name}: input.${f.name},`;
    })
    .join('\n');

  const toPatchLines = userFields
    .map(f => {
      if (f.kind.kind === 'timestamp') {
        return `  if ('${f.name}' in patch) {
    const v = patch.${f.name};
    out.${f.name} = v === null || v === undefined ? v ?? null : Timestamp.fromDate(new Date(v));
  }`;
      }
      if (f.kind.kind === 'vector') {
        return `  if ('${f.name}' in patch) {
    const v = patch.${f.name};
    out.${f.name} = v === null || v === undefined ? v ?? null : vector(v);
  }`;
      }
      return `  if ('${f.name}' in patch) out.${f.name} = patch.${f.name};`;
    })
    .join('\n');

  const helpersBlock = [
    hasTimestamp
      ? `function tsToIso(value: unknown): string | null {
  return value instanceof Timestamp ? value.toDate().toISOString() : null;
}`
      : '',
    hasVector
      ? `function vecToArray(value: unknown): number[] | null {
  return value instanceof VectorValue ? value.toArray() : null;
}`
      : '',
  ]
    .filter(Boolean)
    .join('\n\n');

  return `${HEADER(sourcePath)}
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  ${firestoreImports.join(',\n  ')},
  type DocumentData,
  type QueryConstraint,
} from 'firebase/firestore';
import { z } from 'zod';
import { db } from '@/modules/firebase';
import { useAuthUser } from '@/shared/stores/auth.store';

const COLLECTION = '${c.name}';
const QUERY_KEY = '${KEY}';

export type ${T} = {
  id: string;
${modelFieldLines}
};

export type ${TCreate} = {
${createFieldLines}
};

export type ${TPatch} = Partial<${TCreate}>;

export type ${TFilter} = {
  limit?: number;
};

const docSchema = z.object({
  id: z.string(),
${docSchemaLines}
});

${helpersBlock}

function fromDoc(id: string, data: DocumentData): ${T} {
  const out = {
    id,
${fromDocLines}
  };
  return docSchema.parse(out);
}

function toCreatePayload(input: ${TCreate}, ${c.ownerField}: string) {
  return {
    ${c.ownerField},
${toCreateLines}
${c.managed.map(m => `    ${m}: serverTimestamp(),`).join('\n')}
  };
}

function toUpdatePayload(patch: ${TPatch}) {
  const out: Record<string, unknown> = {${c.managed.includes('updatedAt') ? ' updatedAt: serverTimestamp() ' : ''}};
${toPatchLines}
  return out;
}

export const use${c.typeName}List = (filter?: ${TFilter}) => {
  const user = useAuthUser();
  return useQuery({
    queryKey: [QUERY_KEY, 'list', user?.uid, filter],
    queryFn: async (): Promise<${T}[]> => {
      if (!user) return [];
      const constraints: QueryConstraint[] = [
        where('${c.ownerField}', '==', user.uid),
        orderBy('${orderBy.field}', '${orderBy.dir}'),
      ];
      if (filter?.limit) constraints.push(fbLimit(filter.limit));
      const q = query(collection(db, COLLECTION), ...constraints);
      const snap = await getDocs(q);
      return snap.docs.map(d => fromDoc(d.id, d.data()));
    },
    enabled: !!user,
  });
};

export const use${c.typeName} = (id: string) => {
  const user = useAuthUser();
  return useQuery({
    queryKey: [QUERY_KEY, 'one', id],
    queryFn: async (): Promise<${T} | null> => {
      const ref = doc(db, COLLECTION, id);
      const snap = await getDoc(ref);
      if (!snap.exists()) return null;
      return fromDoc(snap.id, snap.data());
    },
    enabled: !!user && !!id,
  });
};

export const useCreate${c.typeName} = () => {
  const user = useAuthUser();
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (input: ${TCreate}): Promise<string> => {
      if (!user) throw new Error('Not authenticated');
      const ref = await addDoc(
        collection(db, COLLECTION),
        toCreatePayload(input, user.uid),
      );
      return ref.id;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
};

export const useUpdate${c.typeName} = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({
      id,
      patch,
    }: {
      id: string;
      patch: ${TPatch};
    }): Promise<void> => {
      await updateDoc(doc(db, COLLECTION, id), toUpdatePayload(patch));
    },
    onSuccess: (_data, { id }) => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY, 'one', id] });
    },
  });
};

export const useDelete${c.typeName} = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string): Promise<void> => {
      await deleteDoc(doc(db, COLLECTION, id));
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
};
`;
}
