import type { TField, TParsedCollection } from './parse';

const HEADER = (
  source: string,
) => `// AUTO-GENERATED by scripts/codegen/firestore. DO NOT EDIT.
// Source: ${source}
`;

const tsType = (f: TField): string => {
  let base: string;
  switch (f.kind.kind) {
    case 'string':
    case 'timestamp':
      base = 'string';
      break;
    case 'number':
      base = 'number';
      break;
    case 'boolean':
      base = 'boolean';
      break;
    case 'vector':
      base = 'number[]';
      break;
    case 'enum':
      base = f.kind.values.map(v => `'${v}'`).join(' | ');
      break;
  }
  if (f.nullable) base += ' | null';
  return base;
};

export function emitServer(c: TParsedCollection, sourcePath: string): string {
  const T = `T${c.typeName}`;
  const TCreate = `T${c.typeName}CreateInput`;
  const TPatch = `T${c.typeName}UpdatePatch`;
  const TFilter = `T${c.typeName}ListFilter`;

  const userFields = c.fields.filter(
    f => !c.managed.includes(f.name) && f.name !== c.ownerField,
  );

  const hasTimestamp = c.fields.some(
    f => f.kind.kind === 'timestamp' || c.managed.includes(f.name),
  );
  const hasVector = c.fields.some(f => f.kind.kind === 'vector');

  const adminImports = ['FieldValue'];
  if (hasTimestamp) adminImports.push('Timestamp');
  adminImports.push('type DocumentData');
  adminImports.push('type Query');

  const orderBy = c.defaultOrderBy ?? { field: 'createdAt', dir: 'desc' };

  const modelLines = c.fields.map(f => `  ${f.name}: ${tsType(f)};`).join('\n');

  const createLines = userFields
    .map(f => `  ${f.name}${f.optional ? '?' : ''}: ${tsType(f)};`)
    .join('\n');

  const fromDocLines = c.fields
    .map(f => {
      if (f.kind.kind === 'timestamp') {
        if (c.managed.includes(f.name)) {
          return `    ${f.name}: tsToIso(data.${f.name}) ?? '',`;
        }
        return `    ${f.name}: tsToIso(data.${f.name}),`;
      }
      if (f.kind.kind === 'vector') {
        return `    ${f.name}: vecToArray(data.${f.name}),`;
      }
      if (f.nullable) {
        return `    ${f.name}: (data.${f.name} ?? null) as ${tsType(f)},`;
      }
      return `    ${f.name}: data.${f.name} as ${tsType(f)},`;
    })
    .join('\n');

  const toCreateLines = userFields
    .map(f => {
      if (f.kind.kind === 'timestamp') {
        if (f.nullable) {
          return `    ${f.name}: input.${f.name} === null ? null : Timestamp.fromDate(new Date(input.${f.name})),`;
        }
        return `    ${f.name}: Timestamp.fromDate(new Date(input.${f.name})),`;
      }
      if (f.kind.kind === 'vector') {
        if (f.nullable) {
          return `    ${f.name}: input.${f.name} === null ? null : FieldValue.vector(input.${f.name}),`;
        }
        return `    ${f.name}: FieldValue.vector(input.${f.name}),`;
      }
      return `    ${f.name}: input.${f.name},`;
    })
    .join('\n');

  const toPatchLines = userFields
    .map(f => {
      if (f.kind.kind === 'timestamp') {
        return `  if ('${f.name}' in patch) {
    const v = patch.${f.name};
    out.${f.name} = v === null || v === undefined ? v ?? null : Timestamp.fromDate(new Date(v));
  }`;
      }
      if (f.kind.kind === 'vector') {
        return `  if ('${f.name}' in patch) {
    const v = patch.${f.name};
    out.${f.name} = v === null || v === undefined ? v ?? null : FieldValue.vector(v);
  }`;
      }
      return `  if ('${f.name}' in patch) out.${f.name} = patch.${f.name};`;
    })
    .join('\n');

  const helpers = [
    hasTimestamp
      ? `function tsToIso(value: unknown): string | null {
  return value instanceof Timestamp ? value.toDate().toISOString() : null;
}`
      : '',
    hasVector
      ? `function vecToArray(value: unknown): number[] | null {
  if (value && typeof value === 'object' && 'toArray' in value) {
    const out = (value as { toArray: () => unknown }).toArray();
    if (Array.isArray(out)) return out as number[];
  }
  return null;
}`
      : '',
  ]
    .filter(Boolean)
    .join('\n\n');

  return `${HEADER(sourcePath)}
import {
  ${adminImports.join(',\n  ')},
} from 'firebase-admin/firestore';
import { db } from '../../lib/admin';

const COLLECTION = '${c.name}';

export type ${T} = {
  id: string;
${modelLines}
};

export type ${TCreate} = {
  ${c.ownerField}: string;
${createLines}
};

export type ${TPatch} = Partial<Omit<${TCreate}, '${c.ownerField}'>>;

export type ${TFilter} = {
  ${c.ownerField}?: string;
  limit?: number;
};

${helpers}

function fromDoc(id: string, data: DocumentData): ${T} {
  return {
    id,
${fromDocLines}
  };
}

export const ${c.name}Collection = () => db.collection(COLLECTION);

export async function get${c.typeName}(id: string): Promise<${T} | null> {
  const snap = await ${c.name}Collection().doc(id).get();
  if (!snap.exists) return null;
  const data = snap.data();
  if (!data) return null;
  return fromDoc(snap.id, data);
}

export async function list${c.typeName}(
  filter: ${TFilter} = {},
): Promise<${T}[]> {
  let q: Query = ${c.name}Collection();
  if (filter.${c.ownerField}) {
    q = q.where('${c.ownerField}', '==', filter.${c.ownerField});
  }
  q = q.orderBy('${orderBy.field}', '${orderBy.dir}');
  if (filter.limit) q = q.limit(filter.limit);
  const snap = await q.get();
  return snap.docs.map(d => fromDoc(d.id, d.data()));
}

export async function create${c.typeName}(input: ${TCreate}): Promise<string> {
  const { ${c.ownerField}, ...rest } = input;
  const payload = {
    ${c.ownerField},
${toCreateLines.replace(/input\.(\w+)/g, 'rest.$1')}
${c.managed.map(m => `    ${m}: FieldValue.serverTimestamp(),`).join('\n')}
  };
  const ref = await ${c.name}Collection().add(payload);
  return ref.id;
}

export async function update${c.typeName}(
  id: string,
  patch: ${TPatch},
): Promise<void> {
  const out: Record<string, unknown> = {${c.managed.includes('updatedAt') ? ' updatedAt: FieldValue.serverTimestamp() ' : ''}};
${toPatchLines}
  await ${c.name}Collection().doc(id).update(out);
}

export async function delete${c.typeName}(id: string): Promise<void> {
  await ${c.name}Collection().doc(id).delete();
}
`;
}
