import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';

import { parseCollection } from './parse';
import { emitClient } from './emit-client';
import { emitServer } from './emit-server';
import { collections } from '../../../schemas/index';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..', '..', '..');
const CLIENT_OUT = resolve(ROOT, 'src/generated/firestore');
const SERVER_OUT = resolve(ROOT, 'functions/src/generated/firestore');

async function format(source: string, filepath: string): Promise<string> {
  const config = await prettier.resolveConfig(filepath);
  return prettier.format(source, { ...config, filepath });
}

function fileNameFor(name: string): string {
  return name.replace(/[A-Z]/g, m => `-${m.toLowerCase()}`).replace(/^-/, '');
}

async function emitIndex(dir: string, names: string[]): Promise<void> {
  const lines = names.map(n => `export * from './${n}';`).join('\n');
  const body = `// AUTO-GENERATED by scripts/codegen/firestore. DO NOT EDIT.\n${lines}\n`;
  const out = await format(body, resolve(dir, 'index.ts'));
  await writeFile(resolve(dir, 'index.ts'), out, 'utf8');
}

function info(msg: string): void {
  process.stdout.write(`${msg}\n`);
}

async function main(): Promise<void> {
  if (collections.length === 0) {
    info('[firestore-codegen] no collections registered in schemas/index.ts');
    return;
  }

  await rm(CLIENT_OUT, { recursive: true, force: true });
  await rm(SERVER_OUT, { recursive: true, force: true });
  await mkdir(CLIENT_OUT, { recursive: true });
  await mkdir(SERVER_OUT, { recursive: true });

  const fileNames: string[] = [];

  for (const def of collections) {
    const parsed = parseCollection(def);
    const fname = fileNameFor(parsed.name);
    const sourcePath = `schemas/${fname}.schema.ts`;

    const clientFile = resolve(CLIENT_OUT, `${fname}.ts`);
    const serverFile = resolve(SERVER_OUT, `${fname}.ts`);

    const clientSrc = await format(emitClient(parsed, sourcePath), clientFile);
    const serverSrc = await format(emitServer(parsed, sourcePath), serverFile);

    await writeFile(clientFile, clientSrc, 'utf8');
    await writeFile(serverFile, serverSrc, 'utf8');

    fileNames.push(fname);
    info(
      `[firestore-codegen] ${parsed.name} -> ${relative(ROOT, clientFile)}, ${relative(ROOT, serverFile)}`,
    );
  }

  await emitIndex(CLIENT_OUT, fileNames);
  await emitIndex(SERVER_OUT, fileNames);
}

main().catch(err => {
  process.stderr.write(`[firestore-codegen] failed: ${String(err)}\n`);
  process.exit(1);
});
