name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: Lint, Typecheck, Build, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Prettier check
        if: always()
        run: yarn format:check

      - name: Lint
        if: always()
        run: yarn lint

      - name: Typecheck
        if: always()
        run: yarn typecheck

      - name: Build
        if: always()
        run: yarn build

      - name: Unit tests
        if: always()
        run: yarn test
